spring:
  application:
    name: service-b

server:
  port: 8083
  servlet:
    context-path: /service-b

security:
  oauth2:
    resource:
      jwt:
        keyValue: "12345678"
      #id: fooScope
      #serviceId: ${PREFIX:}resource
