# Hello
GET http://localhost:8080/service-a/hello

###



###
# 使用Web Password模式进行认证
POST http://localhost:8080/uaa/oauth/token
Authorization: Basic web web-password
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=web&username=admin&password=password

> {%
client.global.set("access_token", response.body.access_token);
client.log(response.body.access_token);
%}

###
# 访问需要授权的地址
GET http://localhost:8080/uaa/api/testAuth
Authorization: Bearer {{access_token}}

###
# 访问授权用户信息
GET http://localhost:8080/uaa/api/me
Authorization: Bearer {{access_token}}

###

# Hello
GET http://localhost:8080/service-a/hello

###
GET http://localhost:8080/service-a/byIdWithServiceAdmin/1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8080/service-a/byIdWithAdmin/1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8080/service-a/byIdWithAdminAndScope/1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8080/service-a/users/extra
Authorization: Bearer {{access_token}}

###
GET http://localhost:8080/service-a/users/principal
Authorization: Bearer {{access_token}}

###
GET http://localhost:8080/service-a/b/hello
Authorization: Bearer {{access_token}}

###
GET http://localhost:8080/service-a/b/secret
Authorization: Bearer {{access_token}}

###

